/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class lbmmond_json */

#ifndef _Included_lbmmond_json
#define _Included_lbmmond_json
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     lbmmond_json
 * Method:    stat_parser
 * Signature: (Ljava/nio/ByteBuffer;JZC[C)I
 */
JNIEXPORT jint JNICALL Java_lbmmond_1json_stat_1parser
  (JNIEnv *, jobject, jobject, jlong, jboolean, jchar, jcharArray);

#ifdef __cplusplus
}
#endif
#endif
